package com.king.mapper;

import com.king.model.CorporateCulture;

public interface CorporateCultureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_create_cubic_corporate_culture
     *
     * @mbggenerated Fri May 11 15:11:52 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_create_cubic_corporate_culture
     *
     * @mbggenerated Fri May 11 15:11:52 CST 2018
     */
    int insert(CorporateCulture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_create_cubic_corporate_culture
     *
     * @mbggenerated Fri May 11 15:11:52 CST 2018
     */
    int insertSelective(CorporateCulture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_create_cubic_corporate_culture
     *
     * @mbggenerated Fri May 11 15:11:52 CST 2018
     */
    CorporateCulture selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_create_cubic_corporate_culture
     *
     * @mbggenerated Fri May 11 15:11:52 CST 2018
     */
    int updateByPrimaryKeySelective(CorporateCulture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_create_cubic_corporate_culture
     *
     * @mbggenerated Fri May 11 15:11:52 CST 2018
     */
    int updateByPrimaryKey(CorporateCulture record);
}