package com.king.model;

import java.io.Serializable;
import java.util.Date;

public class CorporateCulture implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_create_cubic_corporate_culture.id
     *
     * @mbggenerated Fri May 11 15:11:52 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_create_cubic_corporate_culture.title
     *
     * @mbggenerated Fri May 11 15:11:52 CST 2018
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_create_cubic_corporate_culture.content
     *
     * @mbggenerated Fri May 11 15:11:52 CST 2018
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_create_cubic_corporate_culture.createTime
     *
     * @mbggenerated Fri May 11 15:11:52 CST 2018
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_create_cubic_corporate_culture.updateTime
     *
     * @mbggenerated Fri May 11 15:11:52 CST 2018
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_create_cubic_corporate_culture
     *
     * @mbggenerated Fri May 11 15:11:52 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_create_cubic_corporate_culture.id
     *
     * @return the value of t_create_cubic_corporate_culture.id
     *
     * @mbggenerated Fri May 11 15:11:52 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_create_cubic_corporate_culture.id
     *
     * @param id the value for t_create_cubic_corporate_culture.id
     *
     * @mbggenerated Fri May 11 15:11:52 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_create_cubic_corporate_culture.title
     *
     * @return the value of t_create_cubic_corporate_culture.title
     *
     * @mbggenerated Fri May 11 15:11:52 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_create_cubic_corporate_culture.title
     *
     * @param title the value for t_create_cubic_corporate_culture.title
     *
     * @mbggenerated Fri May 11 15:11:52 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_create_cubic_corporate_culture.content
     *
     * @return the value of t_create_cubic_corporate_culture.content
     *
     * @mbggenerated Fri May 11 15:11:52 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_create_cubic_corporate_culture.content
     *
     * @param content the value for t_create_cubic_corporate_culture.content
     *
     * @mbggenerated Fri May 11 15:11:52 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_create_cubic_corporate_culture.createTime
     *
     * @return the value of t_create_cubic_corporate_culture.createTime
     *
     * @mbggenerated Fri May 11 15:11:52 CST 2018
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_create_cubic_corporate_culture.createTime
     *
     * @param createtime the value for t_create_cubic_corporate_culture.createTime
     *
     * @mbggenerated Fri May 11 15:11:52 CST 2018
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_create_cubic_corporate_culture.updateTime
     *
     * @return the value of t_create_cubic_corporate_culture.updateTime
     *
     * @mbggenerated Fri May 11 15:11:52 CST 2018
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_create_cubic_corporate_culture.updateTime
     *
     * @param updatetime the value for t_create_cubic_corporate_culture.updateTime
     *
     * @mbggenerated Fri May 11 15:11:52 CST 2018
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_create_cubic_corporate_culture
     *
     * @mbggenerated Fri May 11 15:11:52 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", title=").append(title);
        sb.append(", content=").append(content);
        sb.append(", createtime=").append(createtime);
        sb.append(", updatetime=").append(updatetime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}